# This is a basic workflow that is manually triggered

name: build_it

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'type build'
        # Default value if no value is explicitly provided
        default: 'build'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: add nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/NoDreamWeb/index.json -n "GPR" -u NoDreamWeb -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: push nuget package
      run: dotnet nuget push /home/runner/work/ShortenUrl/ShortenUrl/WebTeam.Utility.ShortenUrl/bin/Release/*.nupkg --source "GPR"  --skip-duplicate
